# Generated by Django 4.2.8 on 2024-07-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='disponibilidade',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('NaoDisponivel', 'NaoDisponivel')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
