# Generated by Django 4.2.8 on 2024-07-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0003_rename_alimentos_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
