# Generated by Django 4.2.8 on 2024-08-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Andamento', 'Andamento'), ('Negado', 'Negado'), ('Aceito', 'Aceito')], default='Solicitado', max_length=50)),
            ],
        ),
    ]
