# Generated by Django 4.2.8 on 2024-08-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentes', models.TextField()),
                ('funcao', models.CharField(choices=[('Cozinha', 'Cozinha'), ('Servir almoço', 'Servir almoço'), ('Limpeza', 'Limpeza')], default='Cozinha', max_length=50)),
            ],
        ),
    ]
